### ISSUE TITLE
ambiguous reference to overloaded definition

### ISSUE THREAD

**Issue by darkman13** [adrianhurt/play-api-rest-seed#1]
``` scala
class Log @Inject() (ws: WSClient)(val messagesApi: MessagesApi) extends api.ApiController with I18nSupport {

  def click = GetAction { implicit request =>
    implicit val foramtJson = Json.format[Cookie]
    ok(ws.url([Some url] + request.uri).withHeaders().get().map { response =>
      Ok(Json.obj("status" -> 0, "data" -> Json.toJson(convertCookies(response.cookies))))
    })
  }
}
```

this code generated blow error 

play.sbt.PlayExceptions$CompilationException: Compilation error[ambiguous reference to overloaded definition,
both method ok in trait ApiController of type [A](futObj: scala.concurrent.Future[A], headers: %28String, String%29*)(implicit w: play.api.libs.json.Writes[A])scala.concurrent.Future[api.ApiResult]
and  method ok in trait ApiController of type [A](obj: A, headers: %28String, String%29*)(implicit w: play.api.libs.json.Writes[A])scala.concurrent.Future[api.ApiResult]

how can i use wsclient in controller async??

**Comment by adrianhurt** [comment]
Hi @darkman13. I don't understand what your code is trying to do. Anyway, the method `ok` provided by `ApiController` only accepts objects that are writable to Json. And you have an `Ok` method inside, that returns a `Result` As the API is implemented, forget regular `Ok` and the rest of the methods that return regular `Result` and use `ok` and the rest ones that return `Future[ApiResult]`. Try with something like this:

``` scala
def click = GetAction { implicit request =>
  implicit val foramtJson = Json.format[Cookie]
  WS.url("http://ip.jsontest.com/").get().flatMap { response =>
    ok(Json.obj("status" -> 0, "data" -> Json.toJson(response.cookies))
  } recover {
    case _ => errorInternalServer("ERROR")
  }
}
```
